### ISSUE TITLE
当手机里视频比较多的时候VideoDataSource类onLoadFinished需要很久才能走完，所以导致很卡

### ISSUE THREAD

**Issue by yanjiaxue** [yangpeixing/YPXImagePicker#1]
如题

**Comment by yangpeixing** [comment]
已加入异步操作，不会阻塞主线程

**Comment by yanjiaxue** [comment]
![image](https://user-images.githubusercontent.com/28942728/61860870-45a65b80-aefd-11e9-96f4-feaa0946e7cc.png)
这里保存图片到文件夹在主线程

**Comment by yanjiaxue** [comment]
我手机有很多很小的视频，进入ImagePickAndCropActivity界面很慢，会过好几秒才能进入

**Comment by yangpeixing** [comment]
这里因为是剪裁View，所以只能放在主线程，目前导致卡死的情况是在整合视频和图片的时候，放在了主线程，目前已经优化，下载最新的demo试一下
https://github.com/yangpeixing/YPXImagePicker


------------------ 原始邮件 ------------------
发件人: "yanjiaxue"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 下午4:58
收件人: "yangpeixing/YPXImagePicker"<YPXImagePicker@noreply.github.com>;
抄送: "Y²ang"<313930500@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [yangpeixing/YPXImagePicker] 当手机里视频比较多的时候VideoDataSource类onLoadFinished需要很久才能走完，所以导致很卡 (#1)





 这里保存图片到文件夹在主线程

**Comment by yanjiaxue** [comment]
好的，我看裁剪View分了两部分，一部分裁剪，一部分保存到本地，我个人觉得可以分开来，弄个进度条比较好。

**Comment by yangpeixing** [comment]
针对视频加载缓慢的问题，目前已经解决了
以前是在扫描视频的时候同时扫描缩略图，现在不会重新扫描缩略图，把加载缩略图放到了adapter里


------------------ 原始邮件 ------------------
发件人: "yanjiaxue"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 下午5:00
收件人: "yangpeixing/YPXImagePicker"<YPXImagePicker@noreply.github.com>;
抄送: "Y²ang"<313930500@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [yangpeixing/YPXImagePicker] 当手机里视频比较多的时候VideoDataSource类onLoadFinished需要很久才能走完，所以导致很卡 (#1)




我手机有很多很小的视频，进入ImagePickAndCropActivity界面很慢，会过好几秒才能进入

**Comment by yanjiaxue** [comment]
还有一个问题是，假如手机上一个短视频没有，那么调用showVideo(true)，图片也不能展示出来

**Comment by yangpeixing** [comment]
已经修复，下载最新demo
https://github.com/yangpeixing/YPXImagePicker


邮件太费事，加Q聊：313930500




------------------ 原始邮件 ------------------
发件人: "yanjiaxue"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 下午5:04
收件人: "yangpeixing/YPXImagePicker"<YPXImagePicker@noreply.github.com>;
抄送: "Y²ang"<313930500@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [yangpeixing/YPXImagePicker] 当手机里视频比较多的时候VideoDataSource类onLoadFinished需要很久才能走完，所以导致很卡 (#1)




还有一个问题是，假如手机上一个短视频没有，那么调用showVideo(true)，图片也不能展示出来

**Comment by yangpeixing** [comment]
新版本已替换扫描内核，将原来的多表查询改成了单表查询，速度更快更稳定！
