### ISSUE TITLE
[建议]视频多选和顶部区域预览视频

### ISSUE THREAD

**Issue by llcfays** [yangpeixing/YPXImagePicker#5]
看了下有货，应该也是大佬写的吧，能不能把视频相关的部分也新增进来。
视频多选和顶部区域预览视频。

**Comment by llcfays** [comment]
自己改了改，已经实现了。
感谢大佬。

**Comment by yangpeixing** [comment]
关于视频预览，已经在排期内了，只是最近新项目赶时间耽误了，不好意思啊！

> 看了下有货，应该也是大佬写的吧，能不能把视频相关的部分也新增进来。
> 视频多选和顶部区域预览视频。
