### ISSUE TITLE
小红书样式不能设置单选模式么?

### ISSUE THREAD

**Issue by BoBoJiangs** [yangpeixing/YPXImagePicker#6]
小红书样式不能设置单选模式么?

**Comment by yangpeixing** [comment]
> 小红书样式不能设置单选模式么?

小红书样式需要在头部预览剪裁，不知道你需要的单选模式是什么意思？不需要剪裁？直接回调出去？

**Comment by BoBoJiangs** [comment]
我的意思只裁剪一张 类似.setMaxCount(1) 但是设置这个选择了一张 必选把这个勾选取消了才能再选

**Comment by yangpeixing** [comment]
> 我的意思只裁剪一张 类似.setMaxCount(1) 但是设置这个选择了一张 必选把这个勾选取消了才能再选

我明白了你的意思，你的需求是选中其他的item，自动把之前的选中去掉，这个暂时没有支持这种操作，原因是用户很有可能在滑动的过程中误操作选中，从而丢失了之前选中的图片。如果你的需求一定需要这样，可以在源码里
ImagePickAndCropFragment
中373行左右selectImage方法中
`    private void selectImage(final int position) {
        if (position < 0) {
            return;
        }
        ImageItem selectImageItem = imageItems.get(isShowCamera ? position - 1 : position);
        if (selectImageItem.isSelect()) {
            selectImageItem.setSelect(false);
            removeImageItemFromCropViewList(selectImageItem);
            checkStateBtn();
        } else {
            if (maxCount == 1) {
                lastPressImageItem.setSelect(false);
                lastPressImageItem.setPress(false);
                removeImageItemFromCropViewList(lastPressImageItem);
            } else {
                if (isOverMaxCount()) {
                    return;
                }
            }
            selectImageItem.setSelect(true);
            pressImage(position, false);
            addImageItemToCropViewList(selectImageItem);
        }
        imageGridAdapter.notifyDataSetChanged();
    }`

**Comment by yangpeixing** [comment]
> 我的意思只裁剪一张 类似.setMaxCount(1) 但是设置这个选择了一张 必选把这个勾选取消了才能再选

我明白了你的意思，你的需求是选中其他的item，自动把之前的选中去掉，这个暂时没有支持这种操作，原因是用户很有可能在滑动的过程中误操作选中，从而丢失了之前选中的图片。如果你的需求一定需要这样，可以在源码里
ImagePickAndCropFragment
中373行左右selectImage方法中

`
    private void selectImage(final int position) {
        if (position < 0) {
            return;
        }
        ImageItem selectImageItem = imageItems.get(isShowCamera ? position - 1 : position);
        if (selectImageItem.isSelect()) {
            selectImageItem.setSelect(false);
            removeImageItemFromCropViewList(selectImageItem);
            checkStateBtn();
        } else {
            if (maxCount == 1) {
                lastPressImageItem.setSelect(false);
                lastPressImageItem.setPress(false);
                removeImageItemFromCropViewList(lastPressImageItem);
            } else {
                if (isOverMaxCount()) {
                    return;
                }
            }
            selectImageItem.setSelect(true);
            pressImage(position, false);
            addImageItemToCropViewList(selectImageItem);
        }
        imageGridAdapter.notifyDataSetChanged();
    }
`

**Comment by BoBoJiangs** [comment]
好的


------------------ 原始邮件 ------------------
发件人: "杨培星"<notifications@github.com>;
发送时间: 2019年9月19日(星期四) 下午2:03
收件人: "yangpeixing/YPXImagePicker"<YPXImagePicker@noreply.github.com>;
抄送: "愿得一人心"<819463350@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yangpeixing/YPXImagePicker] 小红书样式不能设置单选模式么? (#6)



 
我的意思只裁剪一张 类似.setMaxCount(1) 但是设置这个选择了一张 必选把这个勾选取消了才能再选
  
我明白了你的意思，你的需求是选中其他的item，自动把之前的选中去掉，这个暂时没有支持这种操作，原因是用户很有可能在滑动的过程中误操作选中，从而丢失了之前选中的图片。如果你的需求一定需要这样，可以在源码里
 ImagePickAndCropFragment
 中373行左右selectImage方法中
     private void selectImage(final int position) { if (position < 0) { return; } ImageItem selectImageItem = imageItems.get(isShowCamera ? position - 1 : position); if (selectImageItem.isSelect()) { selectImageItem.setSelect(false); removeImageItemFromCropViewList(selectImageItem); checkStateBtn(); } else { if (maxCount == 1) { lastPressImageItem.setSelect(false); lastPressImageItem.setPress(false); removeImageItemFromCropViewList(lastPressImageItem); } else { if (isOverMaxCount()) { return; } } selectImageItem.setSelect(true); pressImage(position, false); addImageItemToCropViewList(selectImageItem); } imageGridAdapter.notifyDataSetChanged(); }

**Comment by yangpeixing** [comment]
> 好的
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "杨培星"<notifications@github.com>; 发送时间: 2019年9月19日(星期四) 下午2:03 收件人: "yangpeixing/YPXImagePicker"<YPXImagePicker@noreply.github.com>; 抄送: "愿得一人心"<819463350@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [yangpeixing/YPXImagePicker] 小红书样式不能设置单选模式么? (#6) 我的意思只裁剪一张 类似.setMaxCount(1) 但是设置这个选择了一张 必选把这个勾选取消了才能再选 我明白了你的意思，你的需求是选中其他的item，自动把之前的选中去掉，这个暂时没有支持这种操作，原因是用户很有可能在滑动的过程中误操作选中，从而丢失了之前选中的图片。如果你的需求一定需要这样，可以在源码里 ImagePickAndCropFragment 中373行左右selectImage方法中 private void selectImage(final int position) { if (position < 0) { return; } ImageItem selectImageItem = imageItems.get(isShowCamera ? position - 1 : position); if (selectImageItem.isSelect()) { selectImageItem.setSelect(false); removeImageItemFromCropViewList(selectImageItem); checkStateBtn(); } else { if (maxCount == 1) { lastPressImageItem.setSelect(false); lastPressImageItem.setPress(false); removeImageItemFromCropViewList(lastPressImageItem); } else { if (isOverMaxCount()) { return; } } selectImageItem.setSelect(true); pressImage(position, false); addImageItemToCropViewList(selectImageItem); } imageGridAdapter.notifyDataSetChanged(); } — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

小红书剪裁框架，短期内会有一次更新和调整，到时候可以考虑把这个单选模式加入，感谢你的使用，如果觉得不错的话给个star，谢谢

**Comment by BoBoJiangs** [comment]
恩恩 谢谢 框架不错,会持续关注 感谢你的开源 点赞！！！！！！




------------------ 原始邮件 ------------------
发件人: "杨培星"<notifications@github.com>;
发送时间: 2019年9月19日(星期四) 下午2:07
收件人: "yangpeixing/YPXImagePicker"<YPXImagePicker@noreply.github.com>;
抄送: "愿得一人心"<819463350@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yangpeixing/YPXImagePicker] 小红书样式不能设置单选模式么? (#6)



 
好的
 …
 ------------------ 原始邮件 ------------------ 发件人: "杨培星"notifications@github.com; 发送时间: 2019年9月19日(星期四) 下午2:03 收件人: "yangpeixing/YPXImagePicker"YPXImagePicker@noreply.github.com; 抄送: "愿得一人心"819463350@qq.com;"Author"author@noreply.github.com; 主题: Re: [yangpeixing/YPXImagePicker] 小红书样式不能设置单选模式么? (#6) 我的意思只裁剪一张 类似.setMaxCount(1) 但是设置这个选择了一张 必选把这个勾选取消了才能再选 我明白了你的意思，你的需求是选中其他的item，自动把之前的选中去掉，这个暂时没有支持这种操作，原因是用户很有可能在滑动的过程中误操作选中，从而丢失了之前选中的图片。如果你的需求一定需要这样，可以在源码里 ImagePickAndCropFragment 中373行左右selectImage方法中 private void selectImage(final int position) { if (position < 0) { return; } ImageItem selectImageItem = imageItems.get(isShowCamera ? position - 1 : position); if (selectImageItem.isSelect()) { selectImageItem.setSelect(false); removeImageItemFromCropViewList(selectImageItem); checkStateBtn(); } else { if (maxCount == 1) { lastPressImageItem.setSelect(false); lastPressImageItem.setPress(false); removeImageItemFromCropViewList(lastPressImageItem); } else { if (isOverMaxCount()) { return; } } selectImageItem.setSelect(true); pressImage(position, false); addImageItemToCropViewList(selectImageItem); } imageGridAdapter.notifyDataSetChanged(); } — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
小红书剪裁框架，短期内会有一次更新和调整，到时候可以考虑把这个单选模式加入，感谢你的使用，如果觉得不错的话给个star，谢谢
